type: BTS
use_gpu: true
use_xpu: false
log_frequency: 100
visualdl_frequency: 500
save_frequency: 1
freeze_bn: false

data_path: /path/to/KITTI_bts_train
log_dir: /path/to/output
model_name: BTS

encoder: densenet121
max_depth: 80.0

num_gpus: 1
seed: 120
split: eigen_bts
eval_split: eigen_bts
num_layers: 18
dataset: kitti_supervise
height: 352
width: 704
disparity_smoothness: 0.001
scales: [0, 1, 2, 3]
min_depth: 0.001
use_stereo: false
frame_ids: [0, -1, 1]
eval_mono: true
eval_stereo: false
variance_focus: 0.85

batch_size: 4
learning_rate: 0.0001
start_epoch: 0
num_epochs: 50

load_weights_folder: 
weights_init: weights/resnet18_pretrain
pose_model_input: pairs
pose_model_type: posecnn
png: true

num_workers: 4
load_weights_folder: None
models_to_load: ["encoder", "depth"]

pred_depth_scale_factor: 1
eval_out_dir: None

use_depth_hints: false
depth_hint_path: None

v1_multiscale: false
disable_automasking: false
predictive_mask: false
no_ssim: false
no_eval: false
avg_reprojection: false
find_unused_parameters: false
post_process: false
save_pred_disps: false
eval_eigen_to_benchmark: false
disable_median_scaling: false

